CREATE TABLE IF NOT EXISTS facilities (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY (CACHE 70000),
    cellar          CHAR(26)        NOT NULL,
    institution     VARCHAR(255)    NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX ASYNC IF NOT EXISTS idx_facilities_cellar ON facilities (cellar);
