CREATE TABLE IF NOT EXISTS practice_settings (
    id            BIGINT          GENERATED BY DEFAULT AS IDENTITY (CACHE 1),
    facility_id   BIGINT          NOT NULL,
    sort_order    INT             NOT NULL,
    setting_code  VARCHAR(10)     NOT NULL,
    setting_name  VARCHAR(255)    NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (facility_id, setting_code)
);

CREATE INDEX ASYNC IF NOT EXISTS idx_practice_settings_facility_id_sort_order ON practice_settings (facility_id, sort_order);