CREATE TABLE IF NOT EXISTS practice_setting (
    id            BIGINT          GENERATED BY DEFAULT AS IDENTITY (CACHE 1),
    facility_id   BIGINT          NOT NULL,
    sort_order    INT             NOT NULL,
    setting_code  VARCHAR(10)     NOT NULL,
    setting_name  VARCHAR(255)    NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX ASYNC IF NOT EXISTS idx_practice_setting_facility_id_sort_order ON practice_setting (facility_id, sort_order);