
INSERT INTO ORGANISATIONS (ods, vault, organisation) VALUES ('HCH01', '01KSM3WRPK2D9K04RS92MBYSHT', 'Holby City Hospital');

INSERT INTO ENVIRONMENTS (vault, environment, is_enabled) VALUES ('01KSM3WRPK2D9K04RS92MBYSHT', 'PRODUCTION', 'Y');
INSERT INTO ENVIRONMENTS (vault, environment, is_enabled) VALUES ('01KSM3WRPK2D9K04RS92MBYSHT', 'MOCK', 'N');
INSERT INTO ENVIRONMENTS (vault, environment, is_enabled) VALUES ('01KSM3WRPK2D9K04RS92MBYSHT', 'CERT', 'Y');
INSERT INTO ENVIRONMENTS (vault, environment, is_enabled) VALUES ('01KSM3WRPK2D9K04RS92MBYSHT', 'TRAINING', 'Y');
INSERT INTO ENVIRONMENTS (vault, environment, is_enabled) VALUES ('01KSM3WRPK2D9K04RS92MBYSHT', 'BUILD', 'Y');

